version: '3.8'

services:
  django_backend:
    container_name: django_backend
    image: chienyioma2019/django_react:backend
    ports:
      - 8000:8000
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"

  react_fronend:
    container_name: react_frontend
    image: chienyioma2019/django_reactweb:frontend      
    ports:
      - 3000:3000
    command: bash -c "npm start"
  
