version: '3.8'

services:
  django_backend:
    container_name: django_backend
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"

  react_fronend:
    container_name: react_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: bash -c "npm start"
  